gui:
  worth:
    title: "ɪᴛᴇᴍ ᴘʀɪᴄᴇs (Page {currentPage}/{maxPages})"
    navigation:
      next:
        material: ARROW
        title: "#00F986ɴᴇxᴛ"
        lore:
          - "&fClick to go to the next page"
      back:
        material: ARROW
        title: "#00F986ʙᴀᴄᴋ"
        lore:
          - "&fClick to go to the previous page"
    sorting:
      material: HOPPER
      title: "#00F986ɪᴛᴇᴍ ᴘʀɪᴄᴇs"
      lore:
        - "&fClick to sort"
        - ""
        - "&7({currentSort})"
  sellhistory:
    title: "sᴇʟʟ ʜɪsᴛᴏʀʏ (Page {currentPage}/{maxPages})"
    navigation:
      next:
        material: ARROW
        title: "#00F986ɴᴇxᴛ"
        lore:
          - "&fClick to go to the next page"
      back:
        material: ARROW
        title: "#00F986ʙᴀᴄᴋ"
        lore:
          - "&fClick to go to the previous page"
    sorting:
      material: HOPPER
      title: "#00F986sᴇʟʟ ʜɪsᴛᴏʀʏ"
      lore:
        - "&fClick to sort"
        - ""
        - "&7({currentSort})"

  sell:
    title: "ᴘʟᴀᴄᴇ ɪᴛᴇᴍs ɪɴ ʜᴇʀᴇ ᴛᴏ sᴇʟʟ"
    collect_slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

worth_lore:
  enabled: true
  require_protocollib: true
  add_to_unsellable_items: false
  line: "&7Worth: &a${worth}"

economy:
  internal:
    enabled: true
    starting_balance: 0.0